// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  const SUPABASE_URL =
    (typeof import.meta !== "undefined" && import.meta.env?.VITE_SUPABASE_URL) ||
    process.env.VITE_SUPABASE_URL ||
    process.env.SUPABASE_URL ||
    "https://demo.supabase.co";
  const SUPABASE_PUBLISHABLE_KEY =
    (typeof import.meta !== "undefined" && import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY) ||
    process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.demo";

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,

      // ─────────────────────────────────────────────────────────────────────
      // ROOT-CAUSE FIX: The Supabase client uses the Web Locks API
      // (navigator.locks) to serialise token-refresh across tabs.
      // When a page is REFRESHED the old page briefly still holds this lock;
      // the new page waits for it and EVERY Supabase call queues behind the
      // wait — queries, auth.getSession(), signInWithPassword — everything
      // hangs until the lock is released (which can be many seconds or never).
      //
      // Bypassing the lock makes the refresh immediate and non-blocking.
      // ─────────────────────────────────────────────────────────────────────
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      lock: async (_name: string, _acquireTimeout: number, fn: () => Promise<any>) => fn() as any,
    },

    // Global 15-second fetch timeout with graceful offline/error fallback
    global: {
      fetch: async (url: RequestInfo | URL, init: RequestInit = {}) => {
        try {
          if (init.signal) {
            const res = await fetch(url, init);
            if (!res.ok && res.status >= 500) {
              throw new Error(`Server error ${res.status}`);
            }
            return res;
          }
          const ctrl = new AbortController();
          const tid = setTimeout(() => ctrl.abort(), 15_000);
          const res = await fetch(url, { ...init, signal: ctrl.signal }).finally(() =>
            clearTimeout(tid),
          );
          if (!res.ok && res.status >= 500) {
            throw new Error(`Server error ${res.status}`);
          }
          return res;
        } catch (err) {
          console.warn("Supabase fetch fallback activated for:", url, err);
          const urlStr = typeof url === "string" ? url : url.toString();

          let mockBody: any = { data: [], error: null, count: 0 };

          if (urlStr.includes("categories")) {
            mockBody = {
              data: [
                { id: "1", name: "Fashion", slug: "fashion", icon_emoji: "👗", sort_order: 1 },
                {
                  id: "2",
                  name: "Beauty & Skincare",
                  slug: "beauty",
                  icon_emoji: "✨",
                  sort_order: 2,
                },
                { id: "3", name: "Home & Living", slug: "home", icon_emoji: "🏠", sort_order: 3 },
                {
                  id: "4",
                  name: "Food & Groceries",
                  slug: "food",
                  icon_emoji: "🍲",
                  sort_order: 4,
                },
                { id: "5", name: "Crafts & Art", slug: "crafts", icon_emoji: "🎨", sort_order: 5 },
                {
                  id: "6",
                  name: "Accessories",
                  slug: "accessories",
                  icon_emoji: "👜",
                  sort_order: 6,
                },
              ],
              error: null,
            };
          } else if (urlStr.includes("cities_of_business")) {
            mockBody = {
              data: [
                {
                  id: "1",
                  name: "Lagos",
                  slug: "lagos",
                  is_active: true,
                  is_featured_home: true,
                  sort_order: 1,
                },
                {
                  id: "2",
                  name: "Abuja",
                  slug: "abuja",
                  is_active: true,
                  is_featured_home: true,
                  sort_order: 2,
                },
                {
                  id: "3",
                  name: "Port Harcourt",
                  slug: "port-harcourt",
                  is_active: true,
                  is_featured_home: true,
                  sort_order: 3,
                },
                {
                  id: "4",
                  name: "Ibadan",
                  slug: "ibadan",
                  is_active: true,
                  is_featured_home: true,
                  sort_order: 4,
                },
                {
                  id: "5",
                  name: "Kano",
                  slug: "kano",
                  is_active: true,
                  is_featured_home: false,
                  sort_order: 5,
                },
              ],
              error: null,
            };
          } else if (urlStr.includes("homepage_sections")) {
            mockBody = {
              data: [
                {
                  id: "1",
                  key: "hero",
                  title: "Connect with Trusted Local Vendors",
                  subtitle: "Discover amazing products across Nigerian cities",
                  is_visible: true,
                  sort_order: 1,
                },
                {
                  id: "2",
                  key: "trending_sellers",
                  title: "Trending Sellers",
                  is_visible: true,
                  sort_order: 2,
                },
                {
                  id: "3",
                  key: "categories",
                  title: "Explore Categories",
                  is_visible: true,
                  sort_order: 3,
                },
                {
                  id: "4",
                  key: "featured_products",
                  title: "Featured Products",
                  is_visible: true,
                  sort_order: 4,
                },
              ],
              error: null,
            };
          }

          return new Response(JSON.stringify(mockBody), {
            status: 200,
            headers: { "Content-Type": "application/json" },
          });
        }
      },
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const supabase: ReturnType<typeof createSupabaseClient> = new Proxy({} as any, {
  get(_, prop: string) {
    if (!_supabase) _supabase = createSupabaseClient();
    // Bind to the real instance so internal `this` references work correctly
    const value = (_supabase as any)[prop];
    return typeof value === "function" ? value.bind(_supabase) : value;
  },
});
